


Config = Config or {}
Config.ExtendedSpriteList = {
    -- IDs 0-100
    {id = 0, name = "Blank", category = "General"},
    {id = 1, name = "Standard", category = "General"},
    {id = 2, name = "Standard with Friend", category = "People"},
    {id = 3, name = "White", category = "General"},
    {id = 4, name = "Mission Vehicle", category = "Vehicles"},
    {id = 5, name = "Mission Bike", category = "Vehicles"},
    {id = 6, name = "Player", category = "People"},
    {id = 7, name = "North", category = "General"},
    {id = 8, name = "Waypoint", category = "General"},
    {id = 9, name = "Big Circle", category = "General"},
    {id = 10, name = "Parachute", category = "Activities"},
    {id = 11, name = "Lobby", category = "General"},
    {id = 12, name = "GTA Race", category = "Activities"},
    {id = 13, name = "Deathmatch", category = "Activities"},
    {id = 14, name = "Arm Wrestling", category = "Activities"},
    {id = 15, name = "Ammunition", category = "Services"},
    {id = 16, name = "Strip Club", category = "Entertainment"},
    {id = 17, name = "Barber", category = "Services"},
    {id = 18, name = "Car Mod Shop", category = "Services"},
    {id = 19, name = "Clothes", category = "Services"},
    {id = 20, name = "Tattoo", category = "Services"},
    {id = 21, name = "German Car", category = "Vehicles"},
    {id = 22, name = "Bike", category = "Vehicles"},
    {id = 23, name = "Crew Member", category = "People"},
    {id = 24, name = "Race Finish", category = "Activities"},
    {id = 25, name = "Store", category = "Services"},
    {id = 26, name = "Helicopter", category = "Vehicles"},
    {id = 27, name = "Plane", category = "Vehicles"},
    {id = 28, name = "Boat", category = "Vehicles"},
    {id = 29, name = "Vehicle Sales", category = "Services"},
    {id = 30, name = "Bike Sales", category = "Services"},
    {id = 31, name = "Garage Vehicle", category = "Vehicles"},
    {id = 32, name = "Garage Bike", category = "Vehicles"},
    {id = 33, name = "Actor", category = "People"},
    {id = 34, name = "Camp", category = "Locations"},
    {id = 35, name = "Military", category = "Locations"},
    {id = 36, name = "Gun Shop", category = "Services"},
    {id = 37, name = "Crown", category = "General"},
    {id = 38, name = "Standard with Ring", category = "General"},
    {id = 39, name = "Michael's House", category = "Locations"},
    {id = 40, name = "Trevor's House", category = "Locations"},
    {id = 41, name = "Franklin's House", category = "Locations"},
    {id = 42, name = "Tractor", category = "Vehicles"},
    {id = 43, name = "Tennis", category = "Activities"},
    {id = 44, name = "Golf Flag", category = "Activities"},
    {id = 45, name = "Shooting Range", category = "Activities"},
    {id = 46, name = "Triathlon", category = "Activities"},
    {id = 47, name = "Off-Road Race", category = "Activities"},
    {id = 48, name = "Gang Attack", category = "Activities"},
    {id = 49, name = "Enemy Helicopter", category = "Vehicles"},
    {id = 50, name = "Police Station", category = "Services"},
    {id = 51, name = "Hospital", category = "Services"},
    {id = 52, name = "Armored Truck", category = "Vehicles"},
    {id = 53, name = "Tow Truck", category = "Vehicles"},
    {id = 54, name = "Barber 2", category = "Services"},
    {id = 55, name = "Car Mod Shop 2", category = "Services"},
    {id = 56, name = "Clothes 2", category = "Services"},
    {id = 57, name = "Tattoo 2", category = "Services"},
    {id = 58, name = "Michael", category = "People"},
    {id = 59, name = "Trevor", category = "People"},
    {id = 60, name = "Franklin", category = "People"},
    {id = 61, name = "Fast Food", category = "Services"},
    {id = 62, name = "Lester", category = "People"},
    {id = 63, name = "Omega", category = "People"},
    {id = 64, name = "Tonya", category = "People"},
    {id = 65, name = "Paparazzo", category = "People"},
    {id = 66, name = "Bounty", category = "Activities"},
    {id = 67, name = "Cable Car", category = "Transportation"},
    {id = 68, name = "Cinema", category = "Entertainment"},
    {id = 69, name = "Weed Stash", category = "Misc"},
    {id = 70, name = "Hunting", category = "Activities"},
    {id = 71, name = "Garage", category = "Services"},
    {id = 72, name = "Golf Cart", category = "Vehicles"},
    {id = 73, name = "Drugs Package", category = "Misc"},
    {id = 74, name = "Apartment", category = "Properties"},
    {id = 75, name = "Question Mark", category = "General"},
    {id = 76, name = "Taxi", category = "Transportation"},
    {id = 77, name = "Fuel", category = "Services"},
    {id = 78, name = "Bar", category = "Entertainment"},
    {id = 79, name = "Base Jumping", category = "Activities"},
    {id = 80, name = "Car Wash", category = "Services"},
    {id = 81, name = "Comedy Club", category = "Entertainment"},
    {id = 82, name = "Dart", category = "Activities"},
    {id = 83, name = "Dating", category = "Activities"},
    {id = 84, name = "Epsilon", category = "Misc"},
    {id = 85, name = "Financial", category = "Services"},
    {id = 86, name = "Bank Heist", category = "Activities"},
    {id = 87, name = "Jewelry Heist", category = "Activities"},
    {id = 88, name = "Golf", category = "Activities"},
    {id = 89, name = "Clothes Store", category = "Services"},
    {id = 90, name = "Altruist Cult", category = "Misc"},
    {id = 91, name = "Marijuana Shop", category = "Services"},
    {id = 92, name = "Hangar", category = "Properties"},
    {id = 93, name = "Helipad", category = "Transportation"},
    {id = 94, name = "Jerry Can", category = "Misc"},
    {id = 95, name = "Masks", category = "Services"},
    {id = 96, name = "Heist Setup", category = "Activities"},
    {id = 97, name = "Incapacitated", category = "People"},
    {id = 98, name = "Spawn Point", category = "General"},
    {id = 99, name = "Boilersuit", category = "Misc"},
    {id = 100, name = "Completed", category = "General"},
    
    -- IDs 101-200
    {id = 101, name = "Rockets", category = "Weapons"},
    {id = 102, name = "Garage For Sale", category = "Properties"},
    {id = 103, name = "Health Heart", category = "Health"},
    {id = 104, name = "S&M", category = "Activities"},
    {id = 105, name = "TM", category = "General"},
    {id = 106, name = "Vehicle Deathmatch", category = "Activities"},
    {id = 107, name = "Parachute", category = "Activities"},
    {id = 108, name = "Rampage", category = "Activities"},
    {id = 109, name = "Vinewood Tours", category = "Entertainment"},
    {id = 110, name = "Lamar", category = "People"},
    {id = 111, name = "Brucie", category = "People"},
    {id = 112, name = "Dollar Sign", category = "General"},
    {id = 113, name = "Survival", category = "Activities"},
    {id = 114, name = "Team Deathmatch", category = "Activities"},
    {id = 115, name = "Castle", category = "Locations"},
    {id = 116, name = "Arm Wrestling", category = "Activities"},
    {id = 117, name = "Race", category = "Activities"},
    {id = 118, name = "Deathmatch", category = "Activities"},
    {id = 119, name = "Arm Wrestling", category = "Activities"},
    {id = 120, name = "Premade Deathmatch", category = "Activities"},
    {id = 121, name = "Premade Race", category = "Activities"},
    {id = 122, name = "Premade Vehicle Deathmatch", category = "Activities"},
    {id = 123, name = "Blimp", category = "Vehicles"},
    {id = 124, name = "Repair", category = "Services"},
    {id = 125, name = "Testosterone", category = "Health"},
    {id = 126, name = "Deathmatch", category = "Activities"},
    {id = 127, name = "Race Air", category = "Activities"},
    {id = 128, name = "Race Bicycle", category = "Activities"},
    {id = 129, name = "Race Water", category = "Activities"},
    {id = 130, name = "Race Automobile", category = "Activities"},
    {id = 131, name = "Race Foot", category = "Activities"},
    {id = 132, name = "Garage Full", category = "Properties"},
    {id = 133, name = "Clothes", category = "Services"},
    {id = 134, name = "Default Taxi", category = "Transportation"},
    {id = 135, name = "Franklin", category = "People"},
    {id = 136, name = "Franklin 2", category = "People"},
    {id = 137, name = "Michael", category = "People"},
    {id = 138, name = "Michael 2", category = "People"},
    {id = 139, name = "Trevor", category = "People"},
    {id = 140, name = "Trevor 2", category = "People"},
    {id = 141, name = "Stranger", category = "People"},
    {id = 142, name = "Armored Truck", category = "Vehicles"},
    {id = 143, name = "Tow Truck", category = "Vehicles"},
    {id = 144, name = "Barber", category = "Services"},
    {id = 145, name = "LS Customs", category = "Services"},
    {id = 146, name = "Clothes", category = "Services"},
    {id = 147, name = "Tattoo", category = "Services"},
    {id = 148, name = "Simeon", category = "People"},
    {id = 149, name = "Lester", category = "People"},
    {id = 150, name = "Omega", category = "People"},
    {id = 151, name = "Flight School", category = "Activities"},
    {id = 152, name = "Bail Bond", category = "Activities"},
    {id = 153, name = "Shooting Range", category = "Activities"},
    {id = 154, name = "Solomon", category = "People"},
    {id = 155, name = "Weightlifter", category = "Activities"},
    {id = 156, name = "Strip Club", category = "Entertainment"},
    {id = 157, name = "Tennis", category = "Activities"},
    {id = 158, name = "Triathlon", category = "Activities"},
    {id = 159, name = "Off-Road Race", category = "Activities"},
    {id = 160, name = "Cinema", category = "Entertainment"},
    {id = 161, name = "Music", category = "Entertainment"},
    {id = 162, name = "Marijuana", category = "Misc"},
    {id = 163, name = "Hunting", category = "Activities"},
    {id = 164, name = "Arms Trafficking", category = "Activities"},
    {id = 165, name = "Fairground", category = "Entertainment"},
    {id = 166, name = "Property Management", category = "Properties"},
    {id = 167, name = "Altruist", category = "Misc"},
    {id = 168, name = "Enemy", category = "People"},
    {id = 169, name = "Chop", category = "People"},
    {id = 170, name = "Dead", category = "General"},
    {id = 171, name = "Hooker", category = "People"},
    {id = 172, name = "Friend", category = "People"},
    {id = 173, name = "Mission", category = "Activities"},
    {id = 174, name = "Gun Shop", category = "Services"},
    {id = 175, name = "Health Pack", category = "Health"},
    {id = 176, name = "Boat", category = "Vehicles"},
    {id = 177, name = "Fort Zancudo", category = "Locations"},
    {id = 178, name = "Plane", category = "Vehicles"},
    {id = 179, name = "Submarine", category = "Vehicles"},
    {id = 180, name = "Bike", category = "Vehicles"},
    {id = 181, name = "Parachute", category = "Activities"},
    {id = 182, name = "Jerry Can", category = "Misc"},
    {id = 183, name = "Rocket", category = "Weapons"},
    {id = 184, name = "Weapon", category = "Weapons"},
    {id = 185, name = "Contraband", category = "Misc"},
    {id = 186, name = "Radiation", category = "Misc"},
    {id = 187, name = "Waypoint", category = "General"},
    {id = 188, name = "Weed Farm", category = "Properties"},
    {id = 189, name = "Hunting", category = "Activities"},
    {id = 190, name = "Pool", category = "Activities"},
    {id = 191, name = "Objective", category = "General"},
    {id = 192, name = "Races", category = "Activities"},
    {id = 193, name = "Garage", category = "Properties"},
    {id = 194, name = "Garage 2", category = "Properties"},
    {id = 195, name = "Garage 3", category = "Properties"},
    {id = 196, name = "Garage 4", category = "Properties"},
    {id = 197, name = "Garage Full 2", category = "Properties"},
    {id = 198, name = "Garage Full 3", category = "Properties"},
    {id = 199, name = "Garage Full 4", category = "Properties"},
    {id = 200, name = "Impound", category = "Services"},
    
    -- IDs 201-300
    {id = 201, name = "Impound 2", category = "Services"},
    {id = 202, name = "Random Character", category = "People"},
    {id = 203, name = "Security", category = "Services"},
    {id = 204, name = "Tow Truck", category = "Vehicles"},
    {id = 205, name = "Drive-Thru", category = "Services"},
    {id = 206, name = "Barber 2", category = "Services"},
    {id = 207, name = "Car Mod Shop 2", category = "Services"},
    {id = 208, name = "Clothes 2", category = "Services"},
    {id = 209, name = "Tattoo 2", category = "Services"},
    {id = 210, name = "Epsilon", category = "Misc"},
    {id = 211, name = "Epsilon 2", category = "Misc"},
    {id = 212, name = "Epsilon 3", category = "Misc"},
    {id = 213, name = "Epsilon 4", category = "Misc"},
    {id = 214, name = "Epsilon 5", category = "Misc"},
    {id = 215, name = "Epsilon 6", category = "Misc"},
    {id = 216, name = "Epsilon 7", category = "Misc"},
    {id = 217, name = "Epsilon 8", category = "Misc"},
    {id = 218, name = "Blimp", category = "Vehicles"},
    {id = 219, name = "Repair", category = "Services"},
    {id = 220, name = "Repair 2", category = "Services"},
    {id = 221, name = "Repair 3", category = "Services"},
    {id = 222, name = "Boost", category = "Misc"},
    {id = 223, name = "Boost 2", category = "Misc"},
    {id = 224, name = "Boost 3", category = "Misc"},
    {id = 225, name = "Cop", category = "People"},
    {id = 226, name = "Cop 2", category = "People"},
    {id = 227, name = "Cop 3", category = "People"},
    {id = 228, name = "Construction", category = "Misc"},
    {id = 229, name = "Construction 2", category = "Misc"},
    {id = 230, name = "Camera", category = "Misc"},
    {id = 231, name = "Camera 2", category = "Misc"},
    {id = 232, name = "Camera 3", category = "Misc"},
    {id = 233, name = "Camera 4", category = "Misc"},
    {id = 234, name = "Camera 5", category = "Misc"},
    {id = 235, name = "Camera 6", category = "Misc"},
    {id = 236, name = "Camera 7", category = "Misc"},
    {id = 237, name = "Camera 8", category = "Misc"},
    {id = 238, name = "Camera 9", category = "Misc"},
    {id = 239, name = "Camera 10", category = "Misc"},
    {id = 240, name = "Camera 11", category = "Misc"},
    {id = 241, name = "Camera 12", category = "Misc"},
    {id = 242, name = "Camera 13", category = "Misc"},
    {id = 243, name = "Camera 14", category = "Misc"},
    {id = 244, name = "Camera 15", category = "Misc"},
    {id = 245, name = "Dead", category = "General"},
    {id = 246, name = "Fire", category = "Services"},
    {id = 247, name = "Fire 2", category = "Services"},
    {id = 248, name = "Fire 3", category = "Services"},
    {id = 249, name = "Fire 4", category = "Services"},
    {id = 250, name = "Fire 5", category = "Services"},
    {id = 251, name = "Fire 6", category = "Services"},
    {id = 252, name = "Fire 7", category = "Services"},
    {id = 253, name = "Fire 8", category = "Services"},
    {id = 254, name = "Fire 9", category = "Services"},
    {id = 255, name = "Garage Sale", category = "Properties"},
    {id = 256, name = "Garage Sale 2", category = "Properties"},
    {id = 257, name = "Hangar For Sale", category = "Properties"},
    {id = 258, name = "Tow Truck", category = "Vehicles"},
    {id = 259, name = "Garbage", category = "Services"},
    {id = 260, name = "Garbage 2", category = "Services"},
    {id = 261, name = "Health Pack", category = "Health"},
    {id = 262, name = "Hospital", category = "Services"},
    {id = 263, name = "Hospital 2", category = "Services"},
    {id = 264, name = "Dock", category = "Transportation"},
    {id = 265, name = "Dock 2", category = "Transportation"},
    {id = 266, name = "Dock 3", category = "Transportation"},
    {id = 267, name = "Dock 4", category = "Transportation"},
    {id = 268, name = "Dock For Sale", category = "Properties"},
    {id = 269, name = "Dock For Sale 2", category = "Properties"},
    {id = 270, name = "Dock For Sale 3", category = "Properties"},
    {id = 271, name = "Dock For Sale 4", category = "Properties"},
    {id = 272, name = "Hangar", category = "Properties"},
    {id = 273, name = "Hangar 2", category = "Properties"},
    {id = 274, name = "Helipad", category = "Transportation"},
    {id = 275, name = "Helipad 2", category = "Transportation"},
    {id = 276, name = "Helipad For Sale", category = "Properties"},
    {id = 277, name = "Helipad For Sale 2", category = "Properties"},
    {id = 278, name = "Police", category = "Services"},
    {id = 279, name = "Police 2", category = "Services"},
    {id = 280, name = "Police 3", category = "Services"},
    {id = 281, name = "Police 4", category = "Services"},
    {id = 282, name = "Police 5", category = "Services"},
    {id = 283, name = "Police 6", category = "Services"},
    {id = 284, name = "Police 7", category = "Services"},
    {id = 285, name = "Police 8", category = "Services"},
    {id = 286, name = "Police 9", category = "Services"},
    {id = 287, name = "Police 10", category = "Services"},
    {id = 288, name = "Police 11", category = "Services"},
    {id = 289, name = "Police 12", category = "Services"},
    {id = 290, name = "Police 13", category = "Services"},
    {id = 291, name = "Police 14", category = "Services"},
    {id = 292, name = "Police 15", category = "Services"},
    {id = 293, name = "Police Station", category = "Services"},
    {id = 294, name = "Police Station 2", category = "Services"},
    {id = 295, name = "Police Station 3", category = "Services"},
    {id = 296, name = "Prison", category = "Locations"},
    {id = 297, name = "Prison 2", category = "Locations"},
    {id = 298, name = "Prison 3", category = "Locations"},
    {id = 299, name = "Prison 4", category = "Locations"},
    {id = 300, name = "Prison 5", category = "Locations"},
    
    -- IDs 301-400
    {id = 301, name = "Prison 6", category = "Locations"},
    {id = 302, name = "Prison 7", category = "Locations"},
    {id = 303, name = "Prison 8", category = "Locations"},
    {id = 304, name = "Prison 9", category = "Locations"},
    {id = 305, name = "Prison 10", category = "Locations"},
    {id = 306, name = "Prison 11", category = "Locations"},
    {id = 307, name = "Prison 12", category = "Locations"},
    {id = 308, name = "Prison 13", category = "Locations"},
    {id = 309, name = "Prison 14", category = "Locations"},
    {id = 310, name = "Prison 15", category = "Locations"},
    {id = 311, name = "Prison 16", category = "Locations"},
    {id = 312, name = "Property For Sale", category = "Properties"},
    {id = 313, name = "Property For Sale 2", category = "Properties"},
    {id = 314, name = "Race", category = "Activities"},
    {id = 315, name = "Race 2", category = "Activities"},
    {id = 316, name = "Race 3", category = "Activities"},
    {id = 317, name = "Race 4", category = "Activities"},
    {id = 318, name = "Race 5", category = "Activities"},
    {id = 319, name = "Race 6", category = "Activities"},
    {id = 320, name = "Race 7", category = "Activities"},
    {id = 321, name = "Race 8", category = "Activities"},
    {id = 322, name = "Race Air", category = "Activities"},
    {id = 323, name = "Race Air 2", category = "Activities"},
    {id = 324, name = "Race Air 3", category = "Activities"},
    {id = 325, name = "Race Air 4", category = "Activities"},
    {id = 326, name = "Race Air 5", category = "Activities"},
    {id = 327, name = "Race Air 6", category = "Activities"},
    {id = 328, name = "Race Air 7", category = "Activities"},
    {id = 329, name = "Race Air 8", category = "Activities"},
    {id = 330, name = "Race Bicycle", category = "Activities"},
    {id = 331, name = "Race Bicycle 2", category = "Activities"},
    {id = 332, name = "Race Bicycle 3", category = "Activities"},
    {id = 333, name = "Race Bicycle 4", category = "Activities"},
    {id = 334, name = "Race Bicycle 5", category = "Activities"},
    {id = 335, name = "Race Bicycle 6", category = "Activities"},
    {id = 336, name = "Race Bicycle 7", category = "Activities"},
    {id = 337, name = "Race Bicycle 8", category = "Activities"},
    {id = 338, name = "Race Boat", category = "Activities"},
    {id = 339, name = "Race Boat 2", category = "Activities"},
    {id = 340, name = "Race Boat 3", category = "Activities"},
    {id = 341, name = "Race Boat 4", category = "Activities"},
    {id = 342, name = "Race Boat 5", category = "Activities"},
    {id = 343, name = "Race Boat 6", category = "Activities"},
    {id = 344, name = "Race Boat 7", category = "Activities"},
    {id = 345, name = "Race Boat 8", category = "Activities"},
    {id = 346, name = "Race Car", category = "Activities"},
    {id = 347, name = "Race Car 2", category = "Activities"},
    {id = 348, name = "Race Car 3", category = "Activities"},
    {id = 349, name = "Race Car 4", category = "Activities"},
    {id = 350, name = "Race Car 5", category = "Activities"},
    {id = 351, name = "Race Car 6", category = "Activities"},
    {id = 352, name = "Race Car 7", category = "Activities"},
    {id = 353, name = "Race Car 8", category = "Activities"},
    {id = 354, name = "Race Foot", category = "Activities"},
    {id = 355, name = "Race Foot 2", category = "Activities"},
    {id = 356, name = "Race Foot 3", category = "Activities"},
    {id = 357, name = "Race Foot 4", category = "Activities"},
    {id = 358, name = "Race Foot 5", category = "Activities"},
    {id = 359, name = "Race Foot 6", category = "Activities"},
    {id = 360, name = "Race Foot 7", category = "Activities"},
    {id = 361, name = "Race Foot 8", category = "Activities"},
    {id = 362, name = "Repair", category = "Services"},
    {id = 363, name = "Repair 2", category = "Services"},
    {id = 364, name = "Repair 3", category = "Services"},
    {id = 365, name = "Repair 4", category = "Services"},
    {id = 366, name = "Repair 5", category = "Services"},
    {id = 367, name = "Shooting Range", category = "Activities"},
    {id = 368, name = "Shooting Range 2", category = "Activities"},
    {id = 369, name = "Shooting Range 3", category = "Activities"},
    {id = 370, name = "Shooting Range 4", category = "Activities"},
    {id = 371, name = "Shooting Range 5", category = "Activities"},
    {id = 372, name = "Shooting Range 6", category = "Activities"},
    {id = 373, name = "Shooting Range 7", category = "Activities"},
    {id = 374, name = "Shooting Range 8", category = "Activities"},
    {id = 375, name = "Shooting Range 9", category = "Activities"},
    {id = 376, name = "Spawn Point", category = "General"},
    {id = 377, name = "Survival", category = "Activities"},
    {id = 378, name = "Team Deathmatch", category = "Activities"},
    {id = 379, name = "Tennis", category = "Activities"},
    {id = 380, name = "Tennis 2", category = "Activities"},
    {id = 381, name = "Tennis 3", category = "Activities"},
    {id = 382, name = "Tennis 4", category = "Activities"},
    {id = 383, name = "Tennis 5", category = "Activities"},
    {id = 384, name = "Tennis 6", category = "Activities"},
    {id = 385, name = "Tennis 7", category = "Activities"},
    {id = 386, name = "Tennis 8", category = "Activities"},
    {id = 387, name = "Tennis 9", category = "Activities"},
    {id = 388, name = "Tennis 10", category = "Activities"},
    {id = 389, name = "Triathlon", category = "Activities"},
    {id = 390, name = "Triathlon 2", category = "Activities"},
    {id = 391, name = "Triathlon 3", category = "Activities"},
    {id = 392, name = "Triathlon 4", category = "Activities"},
    {id = 393, name = "Triathlon 5", category = "Activities"},
    {id = 394, name = "Triathlon 6", category = "Activities"},
    {id = 395, name = "Triathlon 7", category = "Activities"},
    {id = 396, name = "Triathlon 8", category = "Activities"},
    {id = 397, name = "Triathlon 9", category = "Activities"},
    {id = 398, name = "Triathlon 10", category = "Activities"},
    {id = 399, name = "UFO", category = "Misc"},
    {id = 400, name = "Weed Farm", category = "Properties"},
    
    -- IDs 401-500
    {id = 401, name = "Weed Farm 2", category = "Properties"},
    {id = 402, name = "Weed Farm 3", category = "Properties"},
    {id = 403, name = "Weed Farm 4", category = "Properties"},
    {id = 404, name = "Weed Farm 5", category = "Properties"},
    {id = 405, name = "Weed Farm 6", category = "Properties"},
    {id = 406, name = "Weed Farm 7", category = "Properties"},
    {id = 407, name = "Weed Farm 8", category = "Properties"},
    {id = 408, name = "Weed Farm 9", category = "Properties"},
    {id = 409, name = "Weed Farm 10", category = "Properties"},
    {id = 410, name = "Weed Farm 11", category = "Properties"},
    {id = 411, name = "Weed Farm 12", category = "Properties"},
    {id = 412, name = "Weed Farm 13", category = "Properties"},
    {id = 413, name = "Weed Farm 14", category = "Properties"},
    {id = 414, name = "Weed Farm 15", category = "Properties"},
    {id = 415, name = "Animal", category = "Misc"},
    {id = 416, name = "Armored Truck", category = "Vehicles"},
    {id = 417, name = "Barber", category = "Services"},
    {id = 418, name = "Car Mod Shop", category = "Services"},
    {id = 419, name = "Clothes", category = "Services"},
    {id = 420, name = "Franklin", category = "People"},
    {id = 421, name = "Bike", category = "Vehicles"},
    {id = 422, name = "Boat", category = "Vehicles"},
    {id = 423, name = "Garage", category = "Properties"},
    {id = 424, name = "Helicopter", category = "Vehicles"},
    {id = 425, name = "Michael", category = "People"},
    {id = 426, name = "Plane", category = "Vehicles"},
    {id = 427, name = "Question Mark", category = "General"},
    {id = 428, name = "Simeon", category = "People"},
    {id = 429, name = "Tattoo", category = "Services"},
    {id = 430, name = "Taxi", category = "Transportation"},
    {id = 431, name = "Trevor", category = "People"},
    {id = 432, name = "Male Hair", category = "Services"},
    {id = 433, name = "Female Hair", category = "Services"},
    {id = 434, name = "Ammunition", category = "Services"},
    {id = 435, name = "Weed Stash", category = "Misc"},
    {id = 436, name = "Hunting", category = "Activities"},
    {id = 437, name = "Arms Trafficking", category = "Activities"},
    {id = 438, name = "Fairground", category = "Entertainment"},
    {id = 439, name = "Property Management", category = "Properties"},
    {id = 440, name = "Altruist", category = "Misc"},
    {id = 441, name = "Enemy", category = "People"},
    {id = 442, name = "Chop", category = "People"},
    {id = 443, name = "Dead", category = "General"},
    {id = 444, name = "Hooker", category = "People"},
    {id = 445, name = "Friend", category = "People"},
    {id = 446, name = "Bound Cage", category = "Misc"},
    {id = 447, name = "Low Ammo", category = "Weapons"},
    {id = 448, name = "Street Race", category = "Activities"},
    {id = 449, name = "Bennys", category = "Services"},
    {id = 450, name = "Race Finish", category = "Activities"},
    {id = 451, name = "Waypoint", category = "General"},
    {id = 452, name = "Stunt", category = "Activities"},
    {id = 453, name = "Stunt Flip", category = "Activities"},
    {id = 454, name = "Stunt Jump", category = "Activities"},
    {id = 455, name = "Stunt Race", category = "Activities"},
    {id = 456, name = "Stunt 5", category = "Activities"},
    {id = 457, name = "Stunt 6", category = "Activities"},
    {id = 458, name = "Stunt 7", category = "Activities"},
    {id = 459, name = "Stunt 8", category = "Activities"},
    {id = 460, name = "Stunt 9", category = "Activities"},
    {id = 461, name = "Stunt 10", category = "Activities"},
    {id = 462, name = "Stunt 11", category = "Activities"},
    {id = 463, name = "Stunt 12", category = "Activities"},
    {id = 464, name = "Stunt 13", category = "Activities"},
    {id = 465, name = "Stunt 14", category = "Activities"},
    {id = 466, name = "Stunt 15", category = "Activities"},
    {id = 467, name = "Stunt 16", category = "Activities"},
    {id = 468, name = "Stunt 17", category = "Activities"},
    {id = 469, name = "Stunt 18", category = "Activities"},
    {id = 470, name = "Stunt 19", category = "Activities"},
    {id = 471, name = "Stunt 20", category = "Activities"},
    {id = 472, name = "Stunt Race 2", category = "Activities"},
    {id = 473, name = "Stunt Race 3", category = "Activities"},
    {id = 474, name = "Stunt Race 4", category = "Activities"},
    {id = 475, name = "Stunt Race 5", category = "Activities"},
    {id = 476, name = "Stunt Race 6", category = "Activities"},
    {id = 477, name = "Stunt Race 7", category = "Activities"},
    {id = 478, name = "Stunt Race 8", category = "Activities"},
    {id = 479, name = "Stunt Race 9", category = "Activities"},
    {id = 480, name = "Stunt Race 10", category = "Activities"},
    {id = 481, name = "Stunt Race 11", category = "Activities"},
    {id = 482, name = "Stunt Race 12", category = "Activities"},
    {id = 483, name = "Stunt Race 13", category = "Activities"},
    {id = 484, name = "Stunt Race 14", category = "Activities"},
    {id = 485, name = "Stunt Race 15", category = "Activities"},
    {id = 486, name = "Stunt Race 16", category = "Activities"},
    {id = 487, name = "Stunt Race 17", category = "Activities"},
    {id = 488, name = "Stunt Race 18", category = "Activities"},
    {id = 489, name = "Stunt Race 19", category = "Activities"},
    {id = 490, name = "Stunt Race 20", category = "Activities"},
    {id = 491, name = "Stunt Race 21", category = "Activities"},
    {id = 492, name = "Stunt Race 22", category = "Activities"},
    {id = 493, name = "Stunt Race 23", category = "Activities"},
    {id = 494, name = "Stunt Race 24", category = "Activities"},
    {id = 495, name = "Stunt Race 25", category = "Activities"},
    {id = 496, name = "Stunt Race 26", category = "Activities"},
    {id = 497, name = "Stunt Race 27", category = "Activities"},
    {id = 498, name = "Stunt Race 28", category = "Activities"},
    {id = 499, name = "Stunt Race 29", category = "Activities"},
    {id = 500, name = "Stunt Race 30", category = "Activities"},
    
    -- IDs 501-600
    {id = 501, name = "Adversary", category = "Activities"},
    {id = 502, name = "Biker Clubhouse", category = "Properties"},
    {id = 503, name = "Biker Crate Drop", category = "Activities"},
    {id = 504, name = "Biker Defend", category = "Activities"},
    {id = 505, name = "Biker Drug Deal", category = "Activities"},
    {id = 506, name = "Biker Rival", category = "Activities"},
    {id = 507, name = "Camera", category = "Misc"},
    {id = 508, name = "Crate Drop", category = "Activities"},
    {id = 509, name = "Destroyed Vehicle", category = "Vehicles"},
    {id = 510, name = "Documents", category = "Misc"},
    {id = 511, name = "Globe", category = "General"},
    {id = 512, name = "Hammer", category = "Weapons"},
    {id = 513, name = "ID Card", category = "Misc"},
    {id = 514, name = "Motorcycle Club", category = "Properties"},
    {id = 515, name = "Race Bike", category = "Activities"},
    {id = 516, name = "Race Flag", category = "Activities"},
    {id = 517, name = "Race Flag 2", category = "Activities"},
    {id = 518, name = "Race Finish Flag", category = "Activities"},
    {id = 519, name = "Secure Package", category = "Misc"},
    {id = 520, name = "Shipping", category = "Transportation"},
    {id = 521, name = "Smuggler Plane", category = "Vehicles"},
    {id = 522, name = "Target", category = "General"},
    {id = 523, name = "Trash", category = "Services"},
    {id = 524, name = "Truck", category = "Vehicles"},
    {id = 525, name = "Contraband", category = "Misc"},
    {id = 526, name = "Yacht", category = "Vehicles"},
    {id = 527, name = "Adversary 2", category = "Activities"},
    {id = 528, name = "Biker Clubhouse 2", category = "Properties"},
    {id = 529, name = "Biker Crate Drop 2", category = "Activities"},
    {id = 530, name = "Biker Defend 2", category = "Activities"},
    {id = 531, name = "Biker Drug Deal 2", category = "Activities"},
    {id = 532, name = "Biker Rival 2", category = "Activities"},
    {id = 533, name = "Camera 2", category = "Misc"},
    {id = 534, name = "Crate Drop 2", category = "Activities"},
    {id = 535, name = "Document 2", category = "Misc"},
    {id = 536, name = "Globe 2", category = "General"},
    {id = 537, name = "Hammer 2", category = "Weapons"},
    {id = 538, name = "ID Card 2", category = "Misc"},
    {id = 539, name = "Motorcycle Club 2", category = "Properties"},
    {id = 540, name = "Race Bike 2", category = "Activities"},
    {id = 541, name = "Race Flag 3", category = "Activities"},
    {id = 542, name = "Race Flag 4", category = "Activities"},
    {id = 543, name = "Race Finish Flag 2", category = "Activities"},
    {id = 544, name = "Secure Package 2", category = "Misc"},
    {id = 545, name = "Shipping 2", category = "Transportation"},
    {id = 546, name = "Smuggler Plane 2", category = "Vehicles"},
    {id = 547, name = "Target 2", category = "General"},
    {id = 548, name = "Trash 2", category = "Services"},
    {id = 549, name = "Truck 2", category = "Vehicles"},
    {id = 550, name = "Contraband 2", category = "Misc"},
    {id = 551, name = "Yacht 2", category = "Vehicles"},
    {id = 552, name = "Bunker", category = "Properties"},
    {id = 553, name = "Bunker 2", category = "Properties"},
    {id = 554, name = "Bunker 3", category = "Properties"},
    {id = 555, name = "Bunker 4", category = "Properties"},
    {id = 556, name = "Bunker 5", category = "Properties"},
    {id = 557, name = "Bunker 6", category = "Properties"},
    {id = 558, name = "Bunker 7", category = "Properties"},
    {id = 559, name = "Bunker 8", category = "Properties"},
    {id = 560, name = "Bunker 9", category = "Properties"},
    {id = 561, name = "Bunker 10", category = "Properties"},
    {id = 562, name = "Bunker 11", category = "Properties"},
    {id = 563, name = "Bunker 12", category = "Properties"},
    {id = 564, name = "Bunker 13", category = "Properties"},
    {id = 565, name = "Bunker 14", category = "Properties"},
    {id = 566, name = "Bunker 15", category = "Properties"},
    {id = 567, name = "Gunrunning", category = "Activities"},
    {id = 568, name = "Gunrunning 2", category = "Activities"},
    {id = 569, name = "Hangar", category = "Properties"},
    {id = 570, name = "Hangar 2", category = "Properties"},
    {id = 571, name = "Hangar 3", category = "Properties"},
    {id = 572, name = "Hangar 4", category = "Properties"},
    {id = 573, name = "Smuggler", category = "Activities"},
    {id = 574, name = "Smuggler 2", category = "Activities"},
    {id = 575, name = "Smuggler 3", category = "Activities"},
    {id = 576, name = "Smuggler 4", category = "Activities"},
    {id = 577, name = "Smuggler 5", category = "Activities"},
    {id = 578, name = "Smuggler 6", category = "Activities"},
    {id = 579, name = "Smuggler 7", category = "Activities"},
    {id = 580, name = "Smuggler 8", category = "Activities"},
    {id = 581, name = "Smuggler 9", category = "Activities"},
    {id = 582, name = "Smuggler 10", category = "Activities"},
    {id = 583, name = "Smuggler 11", category = "Activities"},
    {id = 584, name = "Smuggler 12", category = "Activities"},
    {id = 585, name = "Smuggler 13", category = "Activities"},
    {id = 586, name = "Smuggler 14", category = "Activities"},
    {id = 587, name = "Smuggler 15", category = "Activities"},
    {id = 588, name = "Smuggler 16", category = "Activities"},
    {id = 589, name = "Smuggler 17", category = "Activities"},
    {id = 590, name = "Smuggler 18", category = "Activities"},
    {id = 591, name = "Smuggler 19", category = "Activities"},
    {id = 592, name = "Smuggler 20", category = "Activities"},
    {id = 593, name = "Smuggler 21", category = "Activities"},
    {id = 594, name = "Smuggler 22", category = "Activities"},
    {id = 595, name = "Transform", category = "Activities"},
    {id = 596, name = "Transform 2", category = "Activities"},
    {id = 597, name = "Transform 3", category = "Activities"},
    {id = 598, name = "Transform 4", category = "Activities"},
    {id = 599, name = "Transform 5", category = "Activities"},
    {id = 600, name = "Transform 6", category = "Activities"},
    
    -- IDs 601-700
    {id = 601, name = "Transform 7", category = "Activities"},
    {id = 602, name = "Transform 8", category = "Activities"},
    {id = 603, name = "Transform 9", category = "Activities"},
    {id = 604, name = "Transform 10", category = "Activities"},
    {id = 605, name = "Facility", category = "Properties"},
    {id = 606, name = "Facility 2", category = "Properties"},
    {id = 607, name = "Target 3", category = "General"},
    {id = 608, name = "Doomsday", category = "Activities"},
    {id = 609, name = "Doomsday 2", category = "Activities"},
    {id = 610, name = "Doomsday 3", category = "Activities"},
    {id = 611, name = "Doomsday 4", category = "Activities"},
    {id = 612, name = "Doomsday 5", category = "Activities"},
    {id = 613, name = "Doomsday 6", category = "Activities"},
    {id = 614, name = "Doomsday 7", category = "Activities"},
    {id = 615, name = "Doomsday 8", category = "Activities"},
    {id = 616, name = "Doomsday 9", category = "Activities"},
    {id = 617, name = "Doomsday 10", category = "Activities"},
    {id = 618, name = "Doomsday 11", category = "Activities"},
    {id = 619, name = "Doomsday 12", category = "Activities"},
    {id = 620, name = "Doomsday 13", category = "Activities"},
    {id = 621, name = "Doomsday 14", category = "Activities"},
    {id = 622, name = "Doomsday 15", category = "Activities"},
    {id = 623, name = "Doomsday 16", category = "Activities"},
    {id = 624, name = "Doomsday 17", category = "Activities"},
    {id = 625, name = "Doomsday 18", category = "Activities"},
    {id = 626, name = "Doomsday 19", category = "Activities"},
    {id = 627, name = "Doomsday 20", category = "Activities"},
    {id = 628, name = "Doomsday 21", category = "Activities"},
    {id = 629, name = "Doomsday 22", category = "Activities"},
    {id = 630, name = "Doomsday 23", category = "Activities"},
    {id = 631, name = "Doomsday 24", category = "Activities"},
    {id = 632, name = "Doomsday 25", category = "Activities"},
    {id = 633, name = "Doomsday 26", category = "Activities"},
    {id = 634, name = "Doomsday 27", category = "Activities"},
    {id = 635, name = "Doomsday 28", category = "Activities"},
    {id = 636, name = "Doomsday 29", category = "Activities"},
    {id = 637, name = "Doomsday 30", category = "Activities"},
    {id = 638, name = "Doomsday 31", category = "Activities"},
    {id = 639, name = "Doomsday 32", category = "Activities"},
    {id = 640, name = "Nightclub", category = "Properties"},
    {id = 641, name = "Nightclub 2", category = "Properties"},
    {id = 642, name = "Nightclub 3", category = "Properties"},
    {id = 643, name = "Nightclub 4", category = "Properties"},
    {id = 644, name = "Nightclub 5", category = "Properties"},
    {id = 645, name = "Nightclub 6", category = "Properties"},
    {id = 646, name = "Nightclub 7", category = "Properties"},
    {id = 647, name = "Nightclub 8", category = "Properties"},
    {id = 648, name = "Nightclub 9", category = "Properties"},
    {id = 649, name = "Nightclub 10", category = "Properties"},
    {id = 650, name = "Nightclub 11", category = "Properties"},
    {id = 651, name = "Nightclub 12", category = "Properties"},
    {id = 652, name = "Nightclub 13", category = "Properties"},
    {id = 653, name = "Nightclub 14", category = "Properties"},
    {id = 654, name = "Nightclub 15", category = "Properties"},
    {id = 655, name = "Nightclub 16", category = "Properties"},
    {id = 656, name = "Nightclub 17", category = "Properties"},
    {id = 657, name = "Nightclub 18", category = "Properties"},
    {id = 658, name = "Nightclub 19", category = "Properties"},
    {id = 659, name = "Nightclub 20", category = "Properties"},
    {id = 660, name = "Nightclub 21", category = "Properties"},
    {id = 661, name = "Nightclub 22", category = "Properties"},
    {id = 662, name = "Nightclub 23", category = "Properties"},
    {id = 663, name = "Nightclub 24", category = "Properties"},
    {id = 664, name = "Arena", category = "Properties"},
    {id = 665, name = "Arena 2", category = "Properties"},
    {id = 666, name = "Arena 3", category = "Properties"},
    {id = 667, name = "Arena 4", category = "Properties"},
    {id = 668, name = "Arena 5", category = "Properties"},
    {id = 669, name = "Arena 6", category = "Properties"},
    {id = 670, name = "Arena 7", category = "Properties"},
    {id = 671, name = "Arena 8", category = "Properties"},
    {id = 672, name = "Arena 9", category = "Properties"},
    {id = 673, name = "Arena 10", category = "Properties"},
    {id = 674, name = "Arena 11", category = "Properties"},
    {id = 675, name = "Arena 12", category = "Properties"},
    {id = 676, name = "Arena 13", category = "Properties"},
    {id = 677, name = "Arena 14", category = "Properties"},
    {id = 678, name = "Arena 15", category = "Properties"},
    {id = 679, name = "Arena 16", category = "Properties"},
    {id = 680, name = "Arena 17", category = "Properties"},
    {id = 681, name = "Arena 18", category = "Properties"},
    {id = 682, name = "Arena 19", category = "Properties"},
    {id = 683, name = "Arena 20", category = "Properties"},
    {id = 684, name = "Casino", category = "Properties"},
    {id = 685, name = "Casino 2", category = "Properties"},
    {id = 686, name = "Casino 3", category = "Properties"},
    {id = 687, name = "Casino 4", category = "Properties"},
    {id = 688, name = "Casino 5", category = "Properties"},
    {id = 689, name = "Casino 6", category = "Properties"},
    {id = 690, name = "Casino 7", category = "Properties"},
    {id = 691, name = "Casino 8", category = "Properties"},
    {id = 692, name = "Casino 9", category = "Properties"},
    {id = 693, name = "Casino 10", category = "Properties"},
    {id = 694, name = "Casino 11", category = "Properties"},
    {id = 695, name = "Casino 12", category = "Properties"},
    {id = 696, name = "Casino 13", category = "Properties"},
    {id = 697, name = "Casino 14", category = "Properties"},
    {id = 698, name = "Casino 15", category = "Properties"},
    {id = 699, name = "Casino 16", category = "Properties"},
    {id = 700, name = "Casino 17", category = "Properties"},
    
    -- IDs 701-826
    {id = 701, name = "Casino 18", category = "Properties"},
    {id = 702, name = "Casino 19", category = "Properties"},
    {id = 703, name = "Casino 20", category = "Properties"},
    {id = 704, name = "Casino 21", category = "Properties"},
    {id = 705, name = "Casino 22", category = "Properties"},
    {id = 706, name = "Casino 23", category = "Properties"},
    {id = 707, name = "Casino 24", category = "Properties"},
    {id = 708, name = "Casino 25", category = "Properties"},
    {id = 709, name = "Casino 26", category = "Properties"},
    {id = 710, name = "Casino 27", category = "Properties"},
    {id = 711, name = "Casino 28", category = "Properties"},
    {id = 712, name = "Casino 29", category = "Properties"},
    {id = 713, name = "Casino 30", category = "Properties"},
    {id = 714, name = "Casino 31", category = "Properties"},
    {id = 715, name = "Casino 32", category = "Properties"},
    {id = 716, name = "Casino 33", category = "Properties"},
    {id = 717, name = "Casino 34", category = "Properties"},
    {id = 718, name = "Casino 35", category = "Properties"},
    {id = 719, name = "Casino 36", category = "Properties"},
    {id = 720, name = "Arcade", category = "Properties"},
    {id = 721, name = "Arcade 2", category = "Properties"},
    {id = 722, name = "Arcade 3", category = "Properties"},
    {id = 723, name = "Arcade 4", category = "Properties"},
    {id = 724, name = "Arcade 5", category = "Properties"},
    {id = 725, name = "Arcade 6", category = "Properties"},
    {id = 726, name = "Arcade 7", category = "Properties"},
    {id = 727, name = "Arcade 8", category = "Properties"},
    {id = 728, name = "Arcade 9", category = "Properties"},
    {id = 729, name = "Arcade 10", category = "Properties"},
    {id = 730, name = "Arcade 11", category = "Properties"},
    {id = 731, name = "Arcade 12", category = "Properties"},
    {id = 732, name = "Arcade 13", category = "Properties"},
    {id = 733, name = "Arcade 14", category = "Properties"},
    {id = 734, name = "Arcade 15", category = "Properties"},
    {id = 735, name = "Arcade 16", category = "Properties"},
    {id = 736, name = "Arcade 17", category = "Properties"},
    {id = 737, name = "Arcade 18", category = "Properties"},
    {id = 738, name = "Arcade 19", category = "Properties"},
    {id = 739, name = "Arcade 20", category = "Properties"},
    {id = 740, name = "Arcade 21", category = "Properties"},
    {id = 741, name = "Arcade 22", category = "Properties"},
    {id = 742, name = "Arcade 23", category = "Properties"},
    {id = 743, name = "Arcade 24", category = "Properties"},
    {id = 744, name = "Arcade 25", category = "Properties"},
    {id = 745, name = "Arcade 26", category = "Properties"},
    {id = 746, name = "Arcade 27", category = "Properties"},
    {id = 747, name = "Arcade 28", category = "Properties"},
    {id = 748, name = "Arcade 29", category = "Properties"},
    {id = 749, name = "Arcade 30", category = "Properties"},
    {id = 750, name = "Arcade 31", category = "Properties"},
    {id = 751, name = "Arcade 32", category = "Properties"},
    {id = 752, name = "Arcade 33", category = "Properties"},
    {id = 753, name = "Arcade 34", category = "Properties"},
    {id = 754, name = "Arcade 35", category = "Properties"},
    {id = 755, name = "Arcade 36", category = "Properties"},
    {id = 756, name = "Submarine", category = "Vehicles"},
    {id = 757, name = "Submarine 2", category = "Vehicles"},
    {id = 758, name = "Submarine 3", category = "Vehicles"},
    {id = 759, name = "Submarine 4", category = "Vehicles"},
    {id = 760, name = "Submarine 5", category = "Vehicles"},
    {id = 761, name = "Submarine 6", category = "Vehicles"},
    {id = 762, name = "Submarine 7", category = "Vehicles"},
    {id = 763, name = "Submarine 8", category = "Vehicles"},
    {id = 764, name = "Submarine 9", category = "Vehicles"},
    {id = 765, name = "Submarine 10", category = "Vehicles"},
    {id = 766, name = "Submarine 11", category = "Vehicles"},
    {id = 767, name = "Submarine 12", category = "Vehicles"},
    {id = 768, name = "Submarine 13", category = "Vehicles"},
    {id = 769, name = "Submarine 14", category = "Vehicles"},
    {id = 770, name = "Submarine 15", category = "Vehicles"},
    {id = 771, name = "Submarine 16", category = "Vehicles"},
    {id = 772, name = "Submarine 17", category = "Vehicles"},
    {id = 773, name = "Submarine 18", category = "Vehicles"},
    {id = 774, name = "Submarine 19", category = "Vehicles"},
    {id = 775, name = "Submarine 20", category = "Vehicles"},
    {id = 776, name = "Submarine 21", category = "Vehicles"},
    {id = 777, name = "Submarine 22", category = "Vehicles"},
    {id = 778, name = "Submarine 23", category = "Vehicles"},
    {id = 779, name = "Submarine 24", category = "Vehicles"},
    {id = 780, name = "Auto Shop", category = "Properties"},
    {id = 781, name = "Auto Shop 2", category = "Properties"},
    {id = 782, name = "Auto Shop 3", category = "Properties"},
    {id = 783, name = "Auto Shop 4", category = "Properties"},
    {id = 784, name = "Auto Shop 5", category = "Properties"},
    {id = 785, name = "Auto Shop 6", category = "Properties"},
    {id = 786, name = "Auto Shop 7", category = "Properties"},
    {id = 787, name = "Auto Shop 8", category = "Properties"},
    {id = 788, name = "Auto Shop 9", category = "Properties"},
    {id = 789, name = "Auto Shop 10", category = "Properties"},
    {id = 790, name = "Auto Shop 11", category = "Properties"},
    {id = 791, name = "Auto Shop 12", category = "Properties"},
    {id = 792, name = "Auto Shop 13", category = "Properties"},
    {id = 793, name = "Auto Shop 14", category = "Properties"},
    {id = 794, name = "Auto Shop 15", category = "Properties"},
    {id = 795, name = "Auto Shop 16", category = "Properties"},
    {id = 796, name = "Auto Shop 17", category = "Properties"},
    {id = 797, name = "Auto Shop 18", category = "Properties"},
    {id = 798, name = "Auto Shop 19", category = "Properties"},
    {id = 799, name = "Auto Shop 20", category = "Properties"},
    {id = 800, name = "Agency", category = "Properties"},
    {id = 801, name = "Agency 2", category = "Properties"},
    {id = 802, name = "Agency 3", category = "Properties"},
    {id = 803, name = "Agency 4", category = "Properties"},
    {id = 804, name = "Agency 5", category = "Properties"},
    {id = 805, name = "Agency 6", category = "Properties"},
    {id = 806, name = "Agency 7", category = "Properties"},
    {id = 807, name = "Agency 8", category = "Properties"},
    {id = 808, name = "Agency 9", category = "Properties"},
    {id = 809, name = "Agency 10", category = "Properties"},
    {id = 810, name = "Agency 11", category = "Properties"},
    {id = 811, name = "Agency 12", category = "Properties"},
    {id = 812, name = "Agency 13", category = "Properties"},
    {id = 813, name = "Agency 14", category = "Properties"},
    {id = 814, name = "Agency 15", category = "Properties"},
    {id = 815, name = "Agency 16", category = "Properties"},
    {id = 816, name = "Agency 17", category = "Properties"},
    {id = 817, name = "Agency 18", category = "Properties"},
    {id = 818, name = "Agency 19", category = "Properties"},
    {id = 819, name = "Agency 20", category = "Properties"},
    {id = 820, name = "Agency 21", category = "Properties"},
    {id = 821, name = "Agency 22", category = "Properties"},
    {id = 822, name = "Agency 23", category = "Properties"},
    {id = 823, name = "Agency 24", category = "Properties"},
    {id = 824, name = "Agency 25", category = "Properties"},
    {id = 825, name = "Agency 26", category = "Properties"},
    {id = 826, name = "Agency 27", category = "Properties"}
}

-- Create extended categories based on the comprehensive list
Config.ExtendedBlipCategories = {}
local categoryMap = {}

-- Group sprites by category
for _, sprite in ipairs(Config.ExtendedSpriteList) do
    local category = sprite.category
    if not categoryMap[category] then
        categoryMap[category] = {
            name = category,
            sprites = {}
        }
    end
    table.insert(categoryMap[category].sprites, {id = sprite.id, name = sprite.name})
end

-- Convert map to array
for categoryName, categoryData in pairs(categoryMap) do
    table.insert(Config.ExtendedBlipCategories, categoryData)
end

-- Sort categories alphabetically
table.sort(Config.ExtendedBlipCategories, function(a, b)
    return a.name < b.name
end)

-- Sort sprites within each category by ID
for _, category in ipairs(Config.ExtendedBlipCategories) do
    table.sort(category.sprites, function(a, b)
        return a.id < b.id
    end)
end

-- Create a flattened list of all sprites for backward compatibility
Config.AllExtendedSprites = {}
for _, sprite in ipairs(Config.ExtendedSpriteList) do
    table.insert(Config.AllExtendedSprites, {id = sprite.id, name = sprite.name})
end

-- Sort the flattened list by ID
table.sort(Config.AllExtendedSprites, function(a, b)
    return a.id < b.id
end)

